# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
    - Name: Orderer
      Domain: reliance-network.com
      Specs:
        - Hostname: orderer
        - image: hyperledger/fabric-orderer:latest

PeerOrgs:
    - Name: RelianceInfrastructure
      Domain: infra.reliance-network.com
      EnableNodeOUs: true
      Template:
        count: 1
      Users:
        count: 2

    - Name: ReliancePower
      Domain: power.reliance-network.com
      EnableNodeOUs: true
      Template:
        count: 1
      Users:
        count: 2

    - Name: RelianceCommunications
      Domain: comm.reliance-network.com
      EnableNodeOUs: true
      Template:
        count: 1
      Users:
        count: 2

    - Name: RelianceEntertainment
      Domain: ent.reliance-network.com
      EnableNodeOUs: true
      Template:
        count: 1
      Users:
        count: 2    

    - Name: RelianceCapital
      Domain: cap.reliance-network.com
      EnableNodeOUs: true
      Template:
        count: 1
      Users:
        count: 2