version: '1'

volumes:
    orderer.reliance-network.com
    peer0.infra.reliance-network.com
    peer1.infra.reliance-network.com
    peer0.power.reliance-network.com
    peer1.power.reliance-network.com
    peer0.comm.reliance-network.com
    peer1.comm.reliance-network.com
    peer0.ent.reliance-network.com
    peer1.ent.reliance-network.com
    peer0.cap.reliance-network.com
    peer1.cap.reliance-network.com

networks:
    reliance:

services:
    orderer.reliance-network.com:
        extends:
            file: base/docker-compose-base.yaml
            service: orderer.reliance-network.com
        container_name: orderer.reliance-network.com
        networks:
            - reliance

    peer0.infra.reliance-network.com:
        container_name: peer0.infra.reliance-network.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.infra.reliance-network.com
        networks:
            - reliance

    peer1.infra.reliance-network.com:
        container_name: peer1.infra.reliance-network.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer1.infra.reliance-network.com
        networks:
            - reliance

    peer0.power.reliance-network.com:
        container_name: peer0.power.reliance-network.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.power.reliance-network.com
        networks:
            - reliance

    peer1.power.reliance-network.com:
        container_name: peer1.power.reliance-network.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer1.power.reliance-network.com
        networks:
            - reliance

    peer0.comm.reliance-network.com:
        container_name: peer0.comm.reliance-network.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.comm.reliance-network.com
        networks:
            - reliance

    peer1.comm.reliance-network.com:
        container_name: peer1.comm.reliance-network.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer1.comm.reliance-network.com
        networks:
            - reliance

    peer0.ent.reliance-network.com:
        container_name: peer0.ent.reliance-network.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.ent.reliance-network.com
        networks:
            - reliance

    peer1.ent.reliance-network.com:
        container_name: peer1.ent.reliance-network.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer1.ent.reliance-network.com
        networks:
            - reliance

    peer0.cap.reliance-network.com:
        container_name: peer0.cap.reliance-network.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer0.cap.reliance-network.com
        networks:
            - reliance

    peer1.cap.reliance-network.com:
        container_name: peer1.cap.reliance-network.com
        extends:
            file: base/docker-compose-base.yaml
            service: peer1.cap.reliance-network.com
        networks:
            - reliance

    cli:
        container_name: cli
        image: hyperledger/fabric-tools:latest
        tty: true
        stdin_open: true
        environment:
          - GOPATH=/opt/gopath
          - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
          - CORE_LOGGING_LEVEL=DEBUG
          - CORE_PEER_ID=cli
          - CORE_PEER_ADDRESS=peer0.infra.reliance-network.com:7051
          - CORE_PEER_LOCALMSPID=RelianceInfraMSP
          - CORE_PEER_TLS_ENABLED=true
          - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infra.reliance-network.com/peers/peer0.infra.reliance-network.com/tls/server.crt
          - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infra.reliance-network.com/peers/peer0.infra.reliance-network.com/tls/server.key
          - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infra.reliance-network.com/peers/peer0.infra.reliance-network.com/tls/ca.crt
          - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/infra.reliance-network.com/users/Admin@infra.reliance-network.com/msp
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: /bin/bash
        volumes:
            - /var/run/:/host/var/run/
            - ./../chaincode/:/opt/gopath/src/github.com/chaincode
            - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
            - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts

        depends_on:
            - orderer.reliance-network.com
            - peer0.infra.reliance-network.com
            - peer1.infra.reliance-network.com
            - peer0.power.reliance-network.com
            - peer1.power.reliance-network.com
            - peer0.comm.reliance-network.com
            - peer1.comm.reliance-network.com
            - peer0.ent.reliance-network.com
            - peer1.ent.reliance-network.com
            - peer0.cap.reliance-network.com
            - peer1.cap.reliance-network.com

        networks:
            - reliance